//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace subzicart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBrandPrefix
    {
        public long brand_id { get; set; }
        public string brand_name { get; set; }
        public string brand_prefix { get; set; }
        public string sku_start_range { get; set; }
        public string sku_end_range { get; set; }
        public Nullable<System.DateTime> insdt { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<System.DateTime> updDt { get; set; }
        public Nullable<int> userId { get; set; }
    }
}
