//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace subzicart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCurrencyMaster
    {
        public long cid { get; set; }
        public string currency { get; set; }
        public Nullable<double> rateInUSD { get; set; }
        public Nullable<System.DateTime> insDt { get; set; }
        public Nullable<System.DateTime> updDt { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<double> value { get; set; }
    }
}
