//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace subzicart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompetitorMaster
    {
        public long cmid { get; set; }
        public string company_name { get; set; }
        public string logo_url { get; set; }
        public string website_url { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<double> price { get; set; }
        public string price_currency { get; set; }
        public Nullable<System.DateTime> insDt { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<System.DateTime> updDt { get; set; }
        public Nullable<int> userId { get; set; }
    }
}
