//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace subzicart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategoryMaster
    {
        public int cat_id { get; set; }
        public string cat_name { get; set; }
        public string description { get; set; }
        public Nullable<int> p_cat_id { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<System.DateTime> insDt { get; set; }
        public Nullable<System.DateTime> updDt { get; set; }
    }
}
