//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace subzicart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFullfillmentDetail
    {
        public long fid { get; set; }
        public string name { get; set; }
        public string location { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<double> product_wt { get; set; }
        public string product_wt_unit { get; set; }
        public Nullable<double> product_price { get; set; }
        public string product_price_cr { get; set; }
        public string sku_number { get; set; }
        public Nullable<int> vendor_id { get; set; }
        public string vendor_product_code { get; set; }
        public Nullable<System.DateTime> insDt { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<System.DateTime> updDt { get; set; }
        public Nullable<int> userId { get; set; }
    }
}
