//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace subzicart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImageLog
    {
        public int image_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string image_name { get; set; }
        public string image_desc { get; set; }
        public string image_url { get; set; }
        public byte[] image_binary { get; set; }
        public string isthumb { get; set; }
        public Nullable<int> sort_id { get; set; }
        public Nullable<System.DateTime> insdt { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<System.DateTime> updDt { get; set; }
        public Nullable<System.DateTime> userId { get; set; }
    }
}
