//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace subzicart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogin
    {
        public int id { get; set; }
        public string uname { get; set; }
        public string pswd { get; set; }
        public Nullable<int> company_id { get; set; }
        public string userType { get; set; }
        public Nullable<int> empId { get; set; }
        public Nullable<System.DateTime> lastlogin { get; set; }
        public Nullable<bool> ispwdchanged { get; set; }
        public Nullable<System.DateTime> ispwdchanged_dt { get; set; }
        public string pageAccessRight { get; set; }
        public string subMenuAccessRight { get; set; }
        public string actionRight { get; set; }
    }
}
