//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace subzicart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductGP
    {
        public int gps_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string product_url { get; set; }
        public string redirect_old_url { get; set; }
        public string global_trade_item { get; set; }
        public string manufacture_part_no { get; set; }
        public string gps_gender { get; set; }
        public string gps_age_group { get; set; }
        public string gps_color { get; set; }
        public string gps_size { get; set; }
        public string gps_material { get; set; }
        public string gps_pattern { get; set; }
        public Nullable<int> gps_item_group_id { get; set; }
        public string gps_category { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> insDt { get; set; }
        public Nullable<System.DateTime> updDt { get; set; }
    }
}
