//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace subzicart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductMaster_13082020
    {
        public int productId { get; set; }
        public Nullable<int> catId { get; set; }
        public Nullable<int> subCatId { get; set; }
        public Nullable<int> brandId { get; set; }
        public string productName { get; set; }
        public string SKU { get; set; }
        public string aboutProduct { get; set; }
        public string description { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> costPrice { get; set; }
        public Nullable<int> retailPrice { get; set; }
        public Nullable<int> salePrice { get; set; }
        public string fixedShippingCost { get; set; }
        public string freeShipping { get; set; }
        public string pWeight { get; set; }
        public string pWidth { get; set; }
        public string pHeight { get; set; }
        public string pDepth { get; set; }
        public string searchKeywords { get; set; }
        public string pageTitle { get; set; }
        public string metaKeyword { get; set; }
        public string metaDescription { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> insDt { get; set; }
        public Nullable<System.DateTime> updDt { get; set; }
    }
}
