//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace subzicart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductAvail
    {
        public int pa_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string allow_purchase { get; set; }
        public string is_visible { get; set; }
        public string is_available { get; set; }
        public string track_inventory { get; set; }
        public Nullable<int> current_stock_level { get; set; }
        public Nullable<int> low_stock_level { get; set; }
        public Nullable<System.DateTime> insdt { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<System.DateTime> updDt { get; set; }
        public Nullable<int> userId { get; set; }
    }
}
