//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace subzicart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPageSubMenu
    {
        public int submenu_id { get; set; }
        public string page_url { get; set; }
        public string description { get; set; }
        public Nullable<int> submenurank { get; set; }
        public string submenuheading { get; set; }
        public string active { get; set; }
        public string pmenu { get; set; }
        public Nullable<int> type { get; set; }
        public int menu_id { get; set; }
    }
}
