//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace subzicart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWebpage
    {
        public int page_id { get; set; }
        public string page_url { get; set; }
        public string Description { get; set; }
        public Nullable<int> rank { get; set; }
        public string pageheading { get; set; }
        public string action { get; set; }
        public string active { get; set; }
        public string pmenu { get; set; }
        public string actionNm { get; set; }
        public string ParentNm { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<int> userId { get; set; }
    }
}
